select * from beautyparlor;
\d beautyparlor;
select * from owner;
\d owner;
select * from packages;
\d packages;
select * from services;
\d services;
select * from staffs;
\d staffs;
select * from staff_skill;
\d staff_skill;
select * from appointments;
\d appointments;
select * from customers;
\d customers;
select * from payment;
\d payment;
select * from records;
\d records;